### PR TITLE
Hide selection handles when text changes

### LINKED ISSUE #98: Inserting new line while toolbar being displayed throws exception
## Steps to Reproduce

1. Run the example app
2. Make toolbar visible (by selecting a part of text or tapping somewhere)
3. Insert new line (by pressing enter)

## Logs

```
The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#e1f42](dirty, state: _OverlayEntryWidgetState#c8565):
No child at position TextPosition(offset: 28, affinity: TextAffinity.downstream)
'package:fleather/src/rendering/editable_box.dart':
Failed assertion: line 245 pos 12: 'targetChild != null'

When the exception was thrown, this was the stack: 
#2      RenderEditableContainerBox.childAtPosition (package:fleather/src/rendering/editable_box.dart:245:12)
#3      RenderEditor.getEndpointsForSelection (package:fleather/src/rendering/editor.dart:364:21)
#4      RawEditorState.contextMenuAnchors (package:fleather/src/widgets/editor.dart:1579:22)
#5      defaultContextMenuBuilder (package:fleather/src/widgets/editor.dart:41:34)
#6      RawEditorState._handleSelectionChanged.<anonymous closure> (package:fleather/src/widgets/editor.dart:1121:40)
#7      EditorTextSelectionOverlay._buildToolbar (package:fleather/src/widgets/text_selection.dart:314:35)
#8      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:259:34)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080:27)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
(elided 2 frames from class _AssertionError)
```

### PR DESCRIPTION
**Pull request by Amir-P**
Fixes #98.

### CODE REVIEW

**Comment by Amir-P** [comment]
There is a small issue with tests not finding selection handles which I've commented out. Hope you could help with that @amantoux .

**Comment by Amir-P** [comment]
Test is fixed now. @amantoux

File: packages/fleather/lib/src/widgets/editor.dart [hunk 1]
```diff
@@ -1074,7 +1079,16 @@ class RawEditorState extends EditorState
     super.dispose();
   }
 
+  // Storing the raw text of last textEditingValue
```
Comment (amantoux) [inline packages/fleather/lib/src/widgets/editor.dart:1082]: I'm not sure why we need this. If `TextEditingValue.text` has not changed, then it means `TextEditingValue.selection` has changed, shouldn't this be capture by `_handleSelectionChanges`?

File: packages/fleather/lib/src/widgets/editor_selection_delegate_mixin.dart [hunk 2]
```diff
@@ -81,7 +81,9 @@ mixin RawEditorStateSelectionDelegateMixin on EditorState
 
   @override
   void hideToolbar([bool hideHandles = true]) {
-    if (selectionOverlay?.toolbarIsVisible == true) {
+    if (hideHandles && selectionOverlay?.handlesAreVisible == true) {
```
Comment (amantoux) [inline packages/fleather/lib/src/widgets/editor_selection_delegate_mixin.dart:84]: Do we need to the check `handlesAreVisible` since `hide()` already handles `handles == null`?

File: packages/fleather/lib/src/widgets/text_selection.dart [hunk 3]
```diff
@@ -247,28 +211,36 @@ class EditorTextSelectionOverlay {
   }
 
   /// Whether the handles are currently visible.
-  bool get handlesAreVisible => _handles != null && handlesVisible;
+  bool get handlesAreVisible => _handles != null;
```
Comment (amantoux) [inline packages/fleather/lib/src/widgets/text_selection.dart:214]: Will be *unused* with comment in 'editor_selection_delegate_mixin.dart` L84

File: packages/fleather/lib/src/widgets/editor_selection_delegate_mixin.dart [hunk 4]
```diff
@@ -81,7 +81,9 @@ mixin RawEditorStateSelectionDelegateMixin on EditorState
...
+      selectionOverlay?.hide();
+    } else if (selectionOverlay?.toolbarIsVisible == true) {
```
Comment (amantoux) [inline packages/fleather/lib/src/widgets/editor_selection_delegate_mixin.dart:86]: I prefer `selectionOverlay?.toolbarIsVisible ?? false`

**Review by amantoux — CHANGES_REQUESTED** [review]
OK overall. 
Some slight changes suggested.
Also a question on `editor.dart`

File: packages/fleather/lib/src/widgets/editor.dart (hunk 1 above)
Comment (Amir-P) [reply packages/fleather/lib/src/widgets/editor.dart:1082]: Well, I don't want to detect when selection changed. Here I'm interested in text changes and the `_didChangeTextEditingValue` gets called on controller updates which happens on both text or selection changes. @amantoux

File: packages/fleather/lib/src/widgets/text_selection.dart (hunk 3 above)
Comment (Amir-P) [reply packages/fleather/lib/src/widgets/text_selection.dart:214]: Since `EditorTextSelectionOverlay` is exposed from `EditorState` and `_handles` are private, I think it's better to keep it. WDYT? @amantoux 
```dart
final key = GlobalKey<EditorState>();
print(key.currentState.selectionOverlay.handlesAreVisible);
```

File: packages/fleather/lib/src/widgets/text_selection.dart [hunk 5]
```diff
@@ -335,8 +305,9 @@ class EditorTextSelectionOverlay {
 }
 
 /// This widget represents a single draggable text selection handle.
-class _TextSelectionHandleOverlay extends StatefulWidget {
-  const _TextSelectionHandleOverlay({
+@visibleForTesting
```
[the remark this answers is not in the document]
Comment (Amir-P) [reply packages/fleather/lib/src/widgets/text_selection.dart:308]: Making it private, causes `library_private_types_in_public_api` linter error since it's used in `TextSelectionHandleOverlay`. @amantoux

[the remark this answers is not in the document]
Comment (amantoux) [reply packages/fleather/lib/src/widgets/text_selection.dart:308]: My bad, didn't state that properly
We don't need `@visibleForTesting`

File: packages/fleather/lib/src/widgets/text_selection.dart (hunk 3 above)
Comment (amantoux) [reply packages/fleather/lib/src/widgets/text_selection.dart:214]: My point is, as long as we do not need it we should remove it.

Comment (Amir-P) [reply packages/fleather/lib/src/widgets/text_selection.dart:214]: Is it ok now? But beside internal usages, since it's public, it might be used outside of Fleather. @amantoux

File: packages/fleather/lib/src/widgets/editor.dart (hunk 1 above)
Comment (amantoux) [reply packages/fleather/lib/src/widgets/editor.dart:1082]: My bad again, reviewing this PR on holiday with my kids :)

Why not handle this in `RawEditorStateTextInputClientMixin::updateEditingValueWithDeltas` by adding
```dart
if (data.isNotEmpty) hideToolbar(false);
```

File: packages/fleather/lib/src/widgets/text_selection.dart (hunk 3 above)
Comment (Amir-P) [reply packages/fleather/lib/src/widgets/text_selection.dart:213]: Why? 😁 @amantoux

File: packages/fleather/lib/src/widgets/editor.dart (hunk 1 above)
Comment (Amir-P) [reply packages/fleather/lib/src/widgets/editor.dart:1082]: We can do that. But it doesn't get called when changes come from controller. I'm not sure which one is the correct behavior. WDYT? @amantoux

Comment (amantoux) [reply packages/fleather/lib/src/widgets/editor.dart:1082]: Yes I understand but I think controller-based changes should be programmatic and shouldn't affect how the editor prompts the toolbar to the user.
Do you agree?

Comment (Amir-P) [reply packages/fleather/lib/src/widgets/editor.dart:1082]: Agreed. Will change that. @amantoux

**Comment by Amir-P** [comment]
Can you take a look again? @amantoux

**Comment by amantoux** [comment]
> Can you take a look again? @amantoux

LGTM
Although, you keep `handlesAreVisible`? I think we should not keep it and `EditorTextSelectionOverlay` should not be exported

**Comment by amantoux** [comment]
Any idea why the codecov patch is ok and not the project?  (confused)

**Comment by Amir-P** [comment]
> LGTM Although, you keep `handlesAreVisible`? I think we should not keep it and `EditorTextSelectionOverlay` should not be exported

After checking `EditableTextState`, I see that they're only exposing it for testing. Will do the same or remove it completely if it's not used in tests.

> Any idea why the codecov patch is ok and not the project? (confused)

No idea! We can skip it tho, right? @amantoux

**Comment by Amir-P** [comment]
It's not possible to make `selectionOverlay` private. It's being used by `RawEditorStateSelectionDelegateMixin`. So, I think we should merge this as it is. WDYT? @amantoux

**Comment by amantoux** [comment]
Actually I'm wondering why we are exporting ˋRawEditor`?

**Comment by Amir-P** [comment]
> Actually I'm wondering why we are exporting `RawEditor`?
> @Amir-P

Would it make any difference regarding this PR? But I think it can be useful if you want to get rid of `FleatherShortcuts`, `FleatherActions`, `FleatherHistory` and many other things  when using `FleatherEditor`. @amantoux

**Comment by amantoux** [comment]
> > Actually I'm wondering why we are exporting `RawEditor`?
> > @Amir-P
> 
> Would it make any difference regarding this PR? But I think it can be useful if you want to get rid of `FleatherShortcuts`, `FleatherActions`, `FleatherHistory` and many other things when using `FleatherEditor`. @amantoux

I was thinking the if `EditorTextSelectionOverlay` is not exported, it can be considered as private thus not need to enrich API with helpers since it's usage would be internal. Maybe I'm missing something?

**Comment by Amir-P** [comment]
I consider these API change related discussions out of this PR's scope. There are no API changes in it.
But if you want my opinion on this, I think the `RawEditor` should stay public. As I said, it can be used to build more customizable editor by the developer. @amantoux

**Comment by amantoux** [comment]
> I consider these API change related discussions out of this PR's scope. There are no API changes in it.
> But if you want my opinion on this, I think the `RawEditor` should stay public. As I said, it can be used to build more customizable editor by the developer. @amantoux

`EditorTextSelectionOverlay::handlesAreVisible` is a change of API

**Comment by Amir-P** [comment]
> > I consider these API change related discussions out of this PR's scope. There are no API changes in it.
> > But if you want my opinion on this, I think the `RawEditor` should stay public. As I said, it can be used to build more customizable editor by the developer. @amantoux
> 
> `EditorTextSelectionOverlay::handlesAreVisible` is a change of API

It's already in the codebase. I just changed its implementation. @amantoux

**Comment by amantoux** [comment]
> > > I consider these API change related discussions out of this PR's scope. There are no API changes in it.
> > > But if you want my opinion on this, I think the `RawEditor` should stay public. As I said, it can be used to build more customizable editor by the developer. @amantoux
> > 
> > 
> > `EditorTextSelectionOverlay::handlesAreVisible` is a change of API
> 
> It's already in the codebase. I just changed it's implementation. @amantoux

Yes indeed misread the changes!
