### PR TITLE
Fix toolbar selector positioning

### LINKED ISSUE #262: HeadigStyle Positions
Hi.

When i use Toolbar bottom Sticky,
image

i can't see HeadingStyle like  that
스크린샷 2024-02-01 210843

could you fix when i use bottom sticky toolbar to show heading style?

### LINKED ISSUE #290: When toggling colour selection on Toolbar, assertion received
## Steps to Reproduce

1. I use the toolbar as an overlay itself, a bit like Notion. However, when I toggle text colour option, I get the following assertion:

```
flutter: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 168 pos 12: '_overlay != null': is not true.
flutter: 
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:168:12)
#3      SelectorScopeState.pushSelector.<anonymous closure> (package:fleather/src/widgets/editor_toolbar.dart:1259:20)
#4      _RootZone.run (dart:async/zone.dart:1655:54)
#5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:205:18)
#6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:816:39)
#7      Future._propagateToListeners (dart:async/future_impl.dart:872:11)
#8      Future._propagateToListeners (dart:async/future_impl.dart:771:9)
#9      Future._completeWithValue (dart:async/future_impl.dart:647:5)
#10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:721:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

flutter: ----------------------------------------------------
```
The colour selection menu does not open. 

## Environment
- MacOS
- Flutter version 3.16.4
- Fleather version 1.14.1

### LINKED ISSUE #317: It seems the new overlay usage in heading and color picking etc doesnt work when keyboard is active
Is this a known bug? when keyboard is active the overlay throwing an exception when i tap on headings or color picker

### LINKED ISSUE #323: Can anyone help me with overlay?
The color dialog show in wrong position:
WhatsApp Image 2024-04-13 at 10 32 39

```
import 'package:fleather/fleather.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  FleatherController controller =
      FleatherController(document: ParchmentDocument());

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: GoRouter(
        initialLocation: '/',
        routes: <RouteBase>[
          ShellRoute(
            builder: (_, __, child) {
              return Scaffold(
                backgroundColor: Colors.grey,
                body: Container(
                  color: Colors.white,
                  margin: const EdgeInsets.only(top: 60, left: 200),
                  child: child,
                ),
              );
            },
            routes: [
              GoRoute(
                path: '/',
                builder: (_, __) => Column(
                  children: [
                    FleatherToolbar.basic(controller: controller),
                    Expanded(child: FleatherEditor(controller: controller)),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

```

### PR DESCRIPTION
**Pull request by Amir-P**
- Fixes #317 
- Fixes #290 
- Fixes #323
- Fixes #262 

- [x] Add tests
- [ ] Add breaking change migration guide

### CODE REVIEW

File: packages/fleather/lib/src/widgets/editor_toolbar.dart [hunk 1]
```diff
@@ -1289,3 +1300,117 @@
...
+  Offset getPositionForChild(Size size, Size childSize) {
+    // size: The size of the overlay.
+    // childSize: The size of the menu, when fully open, as determined by
+    // getConstraintsForChild.
+
+    final double y = position.top;
+
+    // Find the ideal horizontal position.
+    double x;
+    if (position.left > position.right) {
```
Comment (amantoux) [inline packages/fleather/lib/src/widgets/editor_toolbar.dart:1350]: Can we implement something that depends on TextDirection? 
We want to align to right if enough space in ltr and the other way round in rtl

File: packages/fleather/lib/src/widgets/editor_toolbar.dart [hunk 2]
```diff
@@ -1242,27 +1221,59 @@ class SelectorScope extends StatefulWidget {
 class SelectorScopeState extends State<SelectorScope> {
   OverlayEntry? _overlayEntry;
 
-  Future<T?> pushSelector<T>(Widget selector, Completer<T?> completer) {
+  /// The [context] should belong to the presentor widget.
+  Future<T?> pushSelector<T>(
+      BuildContext context, Widget selector, Completer<T?> completer,
+      {bool rootOverlay = false}) {
```
Comment (amantoux) [inline packages/fleather/lib/src/widgets/editor_toolbar.dart:1227]: We don't seem to use this option. We should remove it

File: packages/fleather/lib/src/widgets/editor_toolbar.dart [hunk 3]
```diff
@@ -1228,12 +1201,18 @@ class FLIconButton extends StatelessWidget {
...
 
   static SelectorScopeState of(BuildContext context) =>
       context.findAncestorStateOfType<SelectorScopeState>()!;
 
-  final Widget child;
+  static Future<T?> pushSelector<T>(
+          BuildContext context, Widget selector, Completer<T?> completer,
+          {bool rootOverlay = false}) =>
+      SelectorScope.of(context)
+          .pushSelector(context, selector, completer, rootOverlay: rootOverlay);
```
Comment (amantoux) [inline packages/fleather/lib/src/widgets/editor_toolbar.dart:1215]: We don't seem to use this option. We should remove it

File: packages/fleather/lib/src/widgets/editor_toolbar.dart [hunk 4]
```diff
@@ -1242,27 +1221,59 @@ class SelectorScope extends StatefulWidget {
 class SelectorScopeState extends State<SelectorScope> {
   OverlayEntry? _overlayEntry;
 
-  Future<T?> pushSelector<T>(Widget selector, Completer<T?> completer) {
+  /// The [context] should belong to the presentor widget.
```
Comment (amantoux) [inline packages/fleather/lib/src/widgets/editor_toolbar.dart:1224]: Typo = presenter?

File: packages/fleather/lib/src/widgets/editor_toolbar.dart [hunk 5]
```diff
@@ -1242,27 +1221,59 @@ class SelectorScope extends StatefulWidget {
...
+      {bool rootOverlay = false}) {
     _overlayEntry?.remove();
-    final overlayEntry = OverlayEntry(
-      builder: (context) => TapRegion(
-        child: selector,
-        onTapOutside: (_) => completer.complete(null),
+
+    final overlay = Overlay.of(context, rootOverlay: rootOverlay);
+
+    final RenderBox presentor = context.findRenderObject() as RenderBox;
```
Comment (amantoux) [inline packages/fleather/lib/src/widgets/editor_toolbar.dart:1232]: type=presenter?

**Review by amantoux — CHANGES_REQUESTED** [review]
Many thank for this great enhancement!
I have some suggestions

File: packages/fleather/lib/src/widgets/editor_toolbar.dart (hunk 2 above)
Comment (Amir-P) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart:1227]: It's a public API and might be used by users implementing their own custom buttons. @amantoux

File: packages/fleather/lib/src/widgets/editor_toolbar.dart (hunk 3 above)
Comment (Amir-P) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart:1215]: It's a public API and might be used by users implementing their own custom buttons. @amantoux

File: packages/fleather/lib/src/widgets/editor_toolbar.dart (hunk 1 above)
Comment (Amir-P) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart:1350]: That's what I was thinking at first but thought it might be better to follow what Flutter's doing. But will change it since it's easier.

**Comment by Amir-P** [comment]
Thanks for the review! I removed the removal of overlay entry on `didUpdateWidget` (causing a problem for one of the users #290) and applied your suggestions. Could you please take a look again? @amantoux

File: packages/fleather/lib/src/widgets/editor_toolbar.dart (hunk 2 above)
Comment (amantoux) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart:1227]: Ok, but still I think we shouldn't offer the option if not required by a user. It adds complexity for no assessed benefit.
You can keep it if you want though, I don't really mind

File: packages/fleather/lib/src/widgets/editor_toolbar.dart (hunk 3 above)
Comment (amantoux) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart]: Ok, but still I think we shouldn't offer the option if not required by a user. It adds complexity for no assessed benefit.
You can keep it if you want though, I don't really mind

**Review by amantoux — CHANGES_REQUESTED** [review]
PTAL

File: packages/fleather/lib/src/widgets/editor_toolbar.dart (hunk 1 above)
Comment (Amir-P) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart]: Could you please provide the complete code for me to test the behavior?

Comment (amantoux) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart]:
```dart
@override
Offset getPositionForChild(Size size, Size childSize) {
  // size: The size of the overlay.
  // childSize: The size of the menu, when fully open, as determined by
  // getConstraintsForChild.

  final double y = position.top;

  // Find the ideal horizontal position.
  double x;
  if ((textDirection == TextDirection.ltr ? position.right : position.left) > childSize.width) {
    // Menu button is closer to the left edge, so grow to the right, aligned to the left edge.
    x = position.left;
  } else if ((textDirection == TextDirection.ltr ? position.left : position.right) > childSize.width) {
    // Menu button is closer to the right edge, so grow to the left, aligned to the right edge.
    x = size.width - position.right - childSize.width;
  } else {
    switch (textDirection) {
      case TextDirection.rtl:
        x = size.width - position.right - childSize.width;
      case TextDirection.ltr:
        x = position.left;
    }
  }

  final Offset wantedPosition = Offset(x, y);
  final Offset originCenter = position.toRect(Offset.zero & size).center;
  final Iterable<Rect> subScreens =
      DisplayFeatureSubScreen.subScreensInBounds(
          Offset.zero & size, avoidBounds);
  final Rect subScreen = _closestScreen(subScreens, originCenter);
  return _fitInsideScreen(subScreen, childSize, wantedPosition);
}
```

Comment (Amir-P) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart]: It's not working correctly for RTL case but I get the idea. I don't know which one is better. What do you say? @amantoux

Comment (Amir-P) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart]: In fact, it's not even working correctly for RTL right now. :))

**Comment by amantoux** [comment]
> Thanks for the review! I removed the removal of overlay entry on `didUpdateWidget` (causing a problem for one of the users #290) and applied your suggestions. Could you please take a look again? @amantoux

Played with the new behavior, I think it's better than the old one

File: packages/fleather/lib/src/widgets/editor_toolbar.dart (hunk 1 above)
Comment (amantoux) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart]: Difficult for me to test RTL, how bad is it?

Comment (Amir-P) [reply packages/fleather/lib/src/widgets/editor_toolbar.dart]: I think I fixed it. Thanks for the suggestion! @amantoux

**Review by amantoux — APPROVED** [review]
LGTM!
