### PR TITLE
Cache offset and length in document nodes

### LINKED ISSUE #244: Slow typing performance when approx 45k characters used within editor
## Steps to Reproduce

1. Place 45000 characters into editor 
2. Type a sentence
3. Observe lag and delay

## Environment
- MacOS
- Flutter 3.16.4
- Fleather version 1.13.2

### PR DESCRIPTION
**Pull request by Amir-P**
Fixes #244

Performance comparison with master ran locally on an M1 Mac:
```console
Analyzing tests for scrolling
Average Frame Build Time: Target: 87.48 Reference: 87.62
90th Percentile Frame Build Time: Target: 96.96 Reference: 96.93
90th Percentile Frame Build Time: Target: 98.92 Reference: 99.47
Average GPU Frame Time: Target: 0.00 Reference: 0.00
Performance tests found no regression


Analyzing tests for editing
Average Frame Build Time: Target: 129.21 Reference: 762.61
90th Percentile Frame Build Time: Target: 135.17 Reference: 769.02
90th Percentile Frame Build Time: Target: 137.28 Reference: 770.56
Average GPU Frame Time: Target: 0.00 Reference: 0.00
Performance tests found no regression
```

### CODE REVIEW

**Comment by Amir-P** [comment]
This change is supposed to improve the performance of editor specially when editing and having cursor. I was hoping you guys can take a look, test things out, and give feedback on it. Many thanks in advance. @maelchiotti @simonbengtsson

**Comment by simonbengtsson** [comment]
Sure! Tried now both on master and on the perf branch both with and without 100k characters. In summary I didn't really observe any differences. The 100k characters did not seem to matter and the experience was the same both in master and in the perf branch. The editing experience is almost lag free when writing normally so tried spamming the keyboard as fast as I could instead and then some extreme lag is observable. Could very much be related to my persistence code however and not related to fleather editor. 

Attaching a video of that lag when keyboard spamming for reference. Here I have 100k characters in the editor and am using the perf branch but was about the same no matter what. Note that I stopped spamming the keyboard when I saw a visible character at the | line so all characters added after that is added by lag ie when I'm not touching the keyboard.

https://github.com/user-attachments/assets/6a300894-a752-4312-a5ea-26efe3943de7

**Comment by Amir-P** [comment]
Thank you @simonbengtsson for testing it. It's weird that you're not facing any issues with the master maybe your computer is too powerful! According to our benchmark tests we've seen ~3x improvement in average frame build time on macOS (from ~450ms to ~130ms for a frame).
BTW, what a nice looking app you have there!

**Comment by amantoux** [comment]
> Sure! Tried now both on master and on the perf branch both with and without 100k characters. In summary I didn't really observe any differences. The 100k characters did not seem to matter and the experience was the same both in master and in the perf branch. The editing experience is almost lag free when writing normally so tried spamming the keyboard as fast as I could instead and then some extreme lag is observable. Could very much be related to my persistence code however and not related to fleather editor.

The number of paragraphs (`LineNode` or `BlockNode`) makes a huge difference.
If you have 1000+ paragraphs things get pretty sticky

File: packages/parchment/lib/src/document/attributes.dart [hunk 1]
```diff
@@ -254,7 +253,7 @@
   }
 
   @override
-  int get hashCode => hash3(key, scope, value);
+  int get hashCode => Object.hash(key, scope, value);
```
Comment (amantoux) [inline packages/parchment/lib/src/document/attributes.dart:256]: I'm fine with this but it would have been nice to have it in another PR :)

File: packages/parchment/lib/src/document/line.dart [hunk 2]
```diff
@@ -155,7 +155,6 @@ final class LineNode extends ContainerNode<LeafNode> with StyledNode {
   @override
   LeafNode get defaultChild => TextNode();
 
-  // TODO: should be able to cache length and invalidate on any child-related operation
```
Comment (amantoux) [inline packages/parchment/lib/src/document/line.dart:158]: :)

**Review by amantoux — APPROVED** [review]
LGTM!
Awesome performance comming in :)
